-- 列出没有选修过“光北”老师讲授课程的所有学生姓名
SELECT SNAME FROM S  WHERE S.SNO   NOT IN (SELECT SNO FROM SC ,C WHERE C.CNO =   SC.CNO   AND C.TNAME  =  '光北');

-- 列出有两门以上(含两门)不及格(成绩 < 60 分)课程的学生的学号及其姓名
SELECT S.SNO,S.SNAME FROM S,SC,(SELECT SNO FROM SC WHERE GRADE < 60 GROUP BY SNO HAVING COUNT(*) >= 2 )A  WHERE S.SNO=A.SNO AND SC.SNO=A.SNO GROUP BY S.SNO;

-- 列出既学过“11”号课程，又学过“12”号课程的所有学生的姓名
SELECT S.SNAME FROM S,(SELECT SC.SNO FROM SC,C WHERE SC.CNO=C.CNO AND C.CNO IN('11','12') GROUP BY SNO HAVING COUNT(*) = 2 )A WHERE S.SNO=A.SNO;

-- 列出“11”号课成绩比“12”号课成绩高的所有学生的学号，并从小到大排序
SELECT SC1.SNO FROM SC SC1,SC SC2 WHERE SC1.SNO=SC2.SNO AND SC1.CNO='11' AND SC2.CNO='12' AND SC1.GRADE>SC2.GRADE;

-- 列出所有比“张三”年龄大的学生姓名
SELECT SNAME FROM S WHERE SAGE > (SELECT SAGE FROM S WHERE SNAME='张三');

-- 列出所有选修“12”号课程的学生中成绩最高的学生的学号
SELECT S.SNO FROM S,SC   WHERE S.SNO=SC.SNO AND CNO =12  AND GRADE =(SELECT MAX(GRADE) FROM SC WHERE CNO=12) ;

-- 列出所有的学生姓名及其所选修课程的课程号和成绩
SELECT S.SNAME,SC.CNO,GRADE FROM S LEFT JOIN SC ON  S.SNO=SC.SNO;

-- 列出选修四门以上课程的学生学号及总成绩，并要求按照总成绩的降序排列出来
SELECT SC.SNO ,SUM(GRADE) SG FROM SC  GROUP BY SC.SNO HAVING  COUNT(*)>=4 ORDER  BY  SG DESC;
